In [54]:
# 1. Install postgresql
!apt-get -y -qq update
!apt-get -y -qq install postgresql
# 2. Start the service
!service postgresql start

# 3. Create a default database (since 'customer_behavior' won't exist yet)
!sudo -u postgres psql -c "CREATE DATABASE customer_behavior;"
# 4. Set a password for the 'postgres' user to match your code
!sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'pratham0708';"

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
 * Starting PostgreSQL 14 database server
   ...done.
ERROR:  database "customer_behavior" already exists
ALTER ROLE

In [55]:
import pandas as pd
import numpy as np

df = pd.read_csv('customer_shopping_behavior.csv')

In [56]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [58]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [59]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [60]:
df.isnull().sum() / len(df) * 100

Customer ID               0.000000
Age                       0.000000
Gender                    0.000000
Item Purchased            0.000000
Category                  0.000000
Purchase Amount (USD)     0.000000
Location                  0.000000
Size                      0.000000
Color                     0.000000
Season                    0.000000
Review Rating             0.948718
Subscription Status       0.000000
Shipping Type             0.000000
Discount Applied          0.000000
Promo Code Used           0.000000
Previous Purchases        0.000000
Payment Method            0.000000
Frequency of Purchases    0.000000
dtype: float64

In [61]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [62]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [63]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [64]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [65]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [66]:
pd.qcut(df['age'], q=4).value_counts()

age
(17.999, 31.0]    1028
(44.0, 57.0]       986
(57.0, 70.0]       944
(31.0, 44.0]       942
Name: count, dtype: int64

In [67]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)
df[['purchase_frequency_days','frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                       14            Fortnightly
1                       14            Fortnightly
2                        7                 Weekly
3                        7                 Weekly
4                      365               Annually
5                        7                 Weekly
6                       90              Quarterly
7                        7                 Weekly
8                      365               Annually
9                       90              Quarterly

In [68]:
frequent_shoppers = df[df['purchase_frequency_days'] <= 30]

In [69]:
print(frequent_shoppers.head())

   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
5            6   46   Male       Sneakers  Footwear               20

        location size   color  season  review_rating subscription_status  \
0       Kentucky    L    Gray  Winter            3.1                 Yes
1          Maine    L  Maroon  Winter            3.1                 Yes
2  Massachusetts    S  Maroon  Spring            3.1                 Yes
3   Rhode Island    M  Maroon  Spring            3.5                 Yes
5        Wyoming    M   White  Summer            2.9                 Yes

   shipping_type discount_applied promo_code_used  previous_purchases  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3   Next Day Air              Yes             Yes                  49
5       Standard              Yes             Yes                  14

  payment_method frequency_of_purchases    age_group  purchase_frequency_days
0          Venmo            Fortnightly  Middle-aged                       14
1           Cash            Fortnightly  Young Adult                       14
2    Credit Card                 Weekly  Middle-aged                        7
3         PayPal                 Weekly  Young Adult                        7
5          Venmo                 Weekly  Middle-aged                        7

In [70]:
top_customers = df.sort_values(by=['purchase_frequency_days', 'previous_purchases'], ascending=[True, False])

print(top_customers.head(10))

      customer_id  age gender item_purchased     category  purchase_amount  \
140           141   63   Male          Shirt     Clothing               28
290           291   58   Male        T-shirt     Clothing               33
889           890   59   Male           Belt  Accessories               84
992           993   46   Male         Jacket    Outerwear               99
1070         1071   50   Male        Jewelry  Accessories               75
1295         1296   30   Male       Sneakers     Footwear               60
1521         1522   29   Male       Backpack  Accessories               59
1850         1851   51   Male         Gloves  Accessories               76
2059         2060   56   Male         Shorts     Clothing               50
2288         2289   28   Male        Jewelry  Accessories               91

            location size    color  season  review_rating subscription_status  \
140   North Carolina    L   Yellow    Fall            3.9                 Yes
290         Colorado    M   Indigo  Winter            3.7                 Yes
889          Arizona    S    Olive    Fall            2.8                 Yes
992        Louisiana    M     Gray  Winter            4.6                 Yes
1070  North Carolina    M  Magenta  Summer            3.3                  No
1295      New Mexico    M    Olive    Fall            2.8                  No
1521      Washington    M    White  Summer            2.7                  No
1850         Wyoming    S    Black  Winter            2.8                  No
2059      California   XL    Beige  Spring            3.7                  No
2288      California    M   Orange    Fall            3.8                  No

       shipping_type discount_applied promo_code_used  previous_purchases  \
140   2-Day Shipping              Yes             Yes                  50
290         Standard              Yes             Yes                  50
889    Free Shipping              Yes             Yes                  50
992          Express              Yes             Yes                  50
1070   Free Shipping              Yes             Yes                  50
1295        Standard              Yes             Yes                  50
1521  2-Day Shipping              Yes             Yes                  50
1850    Store Pickup               No              No                  50
2059         Express               No              No                  50
2288    Next Day Air               No              No                  50

     payment_method frequency_of_purchases    age_group  \
140     Credit Card                 Weekly       Senior
290          PayPal                 Weekly       Senior
889           Venmo                 Weekly       Senior
992      Debit Card                 Weekly  Middle-aged
1070     Debit Card                 Weekly  Middle-aged
1295         PayPal                 Weekly  Young Adult
1521  Bank Transfer                 Weekly  Young Adult
1850     Debit Card                 Weekly  Middle-aged
2059         PayPal                 Weekly  Middle-aged
2288         PayPal                 Weekly  Young Adult

      purchase_frequency_days
140                         7
290                         7
889                         7
992                         7
1070                        7
1295                        7
1521                        7
1850                        7
2059                        7
2288                        7

In [71]:
df[['discount_applied','promo_code_used']].head(15)

   discount_applied promo_code_used
0               Yes             Yes
1               Yes             Yes
2               Yes             Yes
3               Yes             Yes
4               Yes             Yes
5               Yes             Yes
6               Yes             Yes
7               Yes             Yes
8               Yes             Yes
9               Yes             Yes
10              Yes             Yes
11              Yes             Yes
12              Yes             Yes
13              Yes             Yes
14              Yes             Yes

In [72]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [73]:
df = df.drop('promo_code_used', axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [76]:
from sqlalchemy import create_engine

username = "postgres"
password = "pratham0708"
host = "localhost"
port = "5432"
database = "customer_behavior"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "customer"
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behavior'.

In [77]:
import pandas as pd

sql_query = "SELECT * FROM customer LIMIT 5"
test_df = pd.read_sql(sql_query, engine)

print("Data retrieved from SQL Table:")
print(test_df)

Data retrieved from SQL Table:
   customer_id  age gender item_purchased  category  purchase_amount  \
0            1   55   Male         Blouse  Clothing               53
1            2   19   Male        Sweater  Clothing               64
2            3   50   Male          Jeans  Clothing               73
3            4   21   Male        Sandals  Footwear               90
4            5   45   Male         Blouse  Clothing               49

        location size      color  season  review_rating subscription_status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   shipping_type discount_applied  previous_purchases payment_method  \
0        Express              Yes                  14          Venmo
1        Express              Yes                   2           Cash
2  Free Shipping              Yes                  23    Credit Card
3   Next Day Air              Yes                  49         PayPal
4  Free Shipping              Yes                  31         PayPal

  frequency_of_purchases    age_group  purchase_frequency_days
0            Fortnightly  Middle-aged                       14
1            Fortnightly  Young Adult                       14
2                 Weekly  Middle-aged                        7
3                 Weekly  Young Adult                        7
4               Annually  Middle-aged                      365

In [78]:

df.to_csv('cleaned_customer_data.csv', index=False)

from google.colab import files
files.download('cleaned_customer_data.csv')

In [79]:
print(list(df.columns))

['customer_id', 'age', 'gender', 'item_purchased', 'category', 'purchase_amount', 'location', 'size', 'color', 'season', 'review_rating', 'subscription_status', 'shipping_type', 'discount_applied', 'previous_purchases', 'payment_method', 'frequency_of_purchases', 'age_group', 'purchase_frequency_days']